info: {}
name: verniers_W0p1_0p2_0p3_0_69d73631
settings:
  cross_section: strip_no_ports
  gap: 0.1
  layer_label: TEXT
  straight: straight
  widths:
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  xsize: 100
