info:
  column_pitch: 2
  enclosure: 2
  row_pitch: 2
  xsize: 0.7
  ysize: 0.7
name: via_S0p7_0p7_E2_LVIA1_B_053047f5
settings:
  bbox_offset: 0
  enclosure: 2
  layer: VIA1
  pitch: 2
  size:
  - 0.7
  - 0.7
