info: {}
name: ring_double_G0p2_R10_LX_07be0fa3
settings:
  bend: bend_euler
  coupler_ring: coupler_ring
  cross_section: strip
  gap: 0.2
  length_x: 0.01
  length_y: 0.01
  radius: 10
  straight: straight
