info:
  xsize: 4
  ysize: 4
name: via_stack_S4_4_LHEATER__371e9067
settings:
  correct_size: 1
  layers:
  - HEATER
  - M2
  - MTOP
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 4
  - 4
  slot_horizontal: 0
  slot_vertical: 0
  vias:
  - null
  - via1
  - via2
