info:
  xsize: 11
  ysize: 11
name: via_stack_S11_11_LM2_MT_ff6eecb9
settings:
  correct_size: 1
  layers:
  - M2
  - MTOP
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 11
  - 11
  slot_horizontal: 0
  slot_vertical: 0
  vias:
  - via2
  - null
