info:
  dy: 10.0
  length: 15.708
  radius: 10.0
  route_info_length: 15.708
  route_info_min_bend_radius: 10.0
  route_info_n_bend_90: 1.0
  route_info_strip_length: 15.708
  route_info_type: strip
  route_info_weight: 15.708
  width: 0.5
name: bend_circular_RNone_A90_35590aa7
settings:
  allow_min_radius_violation: 0
  angle: 90.0
  cross_section: strip
