info: {}
name: pad_array_Ppad_C1_R3_CP_a8428924
settings:
  auto_rename_ports: false
  centered_ports: false
  column_pitch: 150
  columns: 1
  layer: MTOP
  pad: pad
  port_orientation: 180
  row_pitch: 150
  rows: 3
  size:
  - 100
  - 100
