info: {}
name: compass_S4_2_LWG_PTelec_2b3a60dd
settings:
  auto_rename_ports: true
  layer: WG
  port_inclusion: 0
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  port_type: electrical
  size:
  - 4
  - 2
