info:
  column_pitch: 2
  enclosure: 1
  radius: 0.35
  row_pitch: 2
  xsize: 0.7
  ysize: 0.7
name: via_circular_R0p35_E1_L_74f6c43d
settings:
  angle_resolution: 2.5
  enclosure: 1
  layer: VIAC
  pitch: 2
  radius: 0.35
