info: {}
name: coupler_bend_R10_CG0p2__a8c01f99
settings:
  bend: bend_circular_all_angle
  bend_output: bend_euler
  coupler_gap: 0.2
  coupling_angle_coverage: 120
  cross_section_inner: strip
  cross_section_outer: strip
  radius: 10
