info: {}
name: straight_heater_meander_2df29628
settings:
  cross_section: strip
  extension_length: 15.0
  heater_taper_length: 10.0
  heater_width: 2.5
  layer_heater: HEATER
  length: 300.0
  spacing: 2.0
  straight_widths:
  - 0.8
  - 0.9
  - 0.8
  taper_length: 10
  via_stack: via_stack_heater_mtop
