info:
  length: 10.0
  width1: 0.5
  width2: 0.5
name: taper_L10_W0p5_WNone_LN_f522d331
settings:
  cross_section: metal_routing
  length: 10.0
  port_names:
  - e1
  - e2
  port_types:
  - electrical
  - electrical
  width1: 0.5
  with_bbox: 1
  with_two_ports: 1
