info:
  xsize: 11
  ysize: 11
name: via_stack_S11_11_LSLAB9_c4c7387b
settings:
  correct_size: true
  layers:
  - SLAB90
  - NPP
  - M1
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 11
  - 11
  slot_horizontal: false
  slot_vertical: false
  vias:
  - null
  - null
  - viac
