info: {}
name: die_S10000_10000_SW100__48b1c773
settings:
  bbox_layer: FLOORPLAN
  die_name: chip99
  draw_corners: 0
  layer: FLOORPLAN
  size:
  - 10000.0
  - 10000.0
  street_length: 1000
  street_width: 100
  text: text
  text_location: SW
  text_size: 100
