info:
  length: 10.186
  min_bend_radius: 11.857
name: add_trenches_Ccoupler_L_e65e8363
settings:
  component: coupler
  cross_section: rib_with_trenches
  layer_component: WG
  layer_trench: DEEP_ETCH
  left: 0
  right: 0
  width_trench: 2.0
