info: {}
name: pad_array_Ppad_SNone_C6_fa910346
settings:
  auto_rename_ports: 0
  centered_ports: 0
  column_pitch: 150
  columns: 6
  layer: MTOP
  pad: pad
  port_orientation: 270
  row_pitch: 150
  rows: 1
  size:
  - 100.0
  - 100.0
