info:
  xsize: 4
  ysize: 4
name: via_stack_S4_4_LHEATER__04e71e19
settings:
  correct_size: true
  layers:
  - HEATER
  - M2
  - MTOP
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 4
  - 4
  slot_horizontal: false
  slot_vertical: false
  vias:
  - null
  - via1
  - via2
