info: {}
name: cdsem_straight_W0p4_0p4_8c7b12fe
settings:
  cross_section: strip_no_ports
  length: 420
  spacing: 7
  text: text_rectangular
  text_size: 1
  widths:
  - 0.4
  - 0.45
  - 0.5
  - 0.6
  - 0.8
  - 1
