info: {}
name: cdsem_straight_W0p4_0p4_ac74fcb4
settings:
  cross_section: strip
  length: 420.0
  spacing: 7.0
  text: text_rectangular
  text_size: 1
  widths:
  - 0.4
  - 0.45
  - 0.5
  - 0.6
  - 0.8
  - 1.0
