info:
  xsize: 11.0
  ysize: 11.0
name: via_stack_S11_11_LSLAB9_138d3e37
settings:
  correct_size: 1
  layers:
  - SLAB90
  - M1
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 11.0
  - 11.0
  slot_horizontal: 1
  slot_vertical: 0
  vias:
  - viac
  - via1
