info: {}
name: ring_single_G0p2_R10_LX_1ab45a89
settings:
  bend: bend_euler
  coupler_ring: coupler_ring
  cross_section: strip
  gap: 0.2
  length_x: 4.0
  length_y: 0.6
  radius: 10.0
  straight: straight
