info:
  area: 80
  num_squares: 750
  xsize: 10
  ysize: 8
name: snspd_WW0p2_WP0p6_S10_8_6a8ca92d
settings:
  layer:
  - 1
  - 0
  port_type: electrical
  size:
  - 10
  - 8
  terminals_same_side: 0
  turn_ratio: 4
  wire_pitch: 0.6
  wire_width: 0.2
