info:
  xsize: 11.0
  ysize: 11.0
name: via_stack_S11_11_LSLAB9_faa7856f
settings:
  correct_size: 1
  layers:
  - SLAB90
  - NPP
  - M1
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 11.0
  - 11.0
  slot_horizontal: 0
  slot_vertical: 0
  vias:
  - null
  - null
  - viac
