info:
  size:
  - 80
  - 80
  xsize: 80
  ysize: 80
name: pad_Spad_size_LMTOP_BLN_98082d0a
settings:
  layer: MTOP
  port_inclusion: 0
  port_orientation: 0
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  port_type: pad
  size: pad_size
