info: {}
name: seal_ring_segmented_S50_1db576ee
settings:
  corner: via_stack_corner45_extended
  length_segment: 10
  size:
  - 500
  - 500
  spacing_segment: 2
  via_stack: via_stack_m1_mtop
  width_segment: 3
  with_east: 1
  with_north: 1
  with_south: 1
  with_west: 1
