info: {}
name: mmi1x2_WNone_WT1_LT10_L_4e0f7121
settings:
  cross_section: strip
  gap_mmi: 0.25
  length_mmi: 5.5
  length_taper: 10.0
  straight: straight
  taper: taper
  width_mmi: 2.5
  width_taper: 1.0
