info:
  xsize: 11
  ysize: 11
name: via_stack_S11_11_LWG_NP_008a56e9
settings:
  correct_size: true
  layers:
  - WG
  - NPP
  - M1
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 11
  - 11
  slot_horizontal: false
  slot_vertical: false
  vias:
  - null
  - null
  - viac
