info:
  dy: 0.0
  length: 42.817
  min_bend_radius: 9.086
  radius: 10.0
  route_info_length: 42.817
  route_info_min_bend_radius: 9.086
  route_info_n_bend_90: 2.0
  route_info_strip_length: 42.817
  route_info_type: strip
  route_info_weight: 42.817
  width: 0.5
name: bend_euler_RNone_A180_P_a75aec30
settings:
  allow_min_radius_violation: 0
  angle: 180
  cross_section: strip
  p: 0.5
  with_arc_floorplan: 1
